custom:
# ;ä¸è¦éšæ„æ”¹å˜å…³é”®å­—ï¼Œå¦åˆ™ä¼šå¯¼è‡´å‡ºé”™
# ;acl4SSRè§„åˆ™


# ;å»å¹¿å‘Šï¼šæ”¯æŒ
# ;è‡ªåŠ¨æµ‹é€Ÿï¼šæ”¯æŒ
# ;å¾®è½¯åˆ†æµï¼šæ”¯æŒ
# ;è‹¹æœåˆ†æµï¼šæ”¯æŒ
# ;å¢å¼ºä¸­å›½IPæ®µï¼šæ”¯æŒ
# ;å¢å¼ºå›½å¤–GFWï¼šæ”¯æŒ
# ;å›½é™…åˆ°è¾¾ï¼šæ”¯æŒ

# ;è®¾ç½®è§„åˆ™æ ‡å¿—ä½
# ;è§£å†³DNSæ³„éœ²ï¼Œåˆ†æµç¾¤ç»„
rulesets:
  enabled: true
  overwrite_original_rules: true
  update_ruleset_on_request: false
  rulesets:
  - {ruleset: "DOMAIN-SUFFIX,yaoyy.moe", group: "ğŸ¯ å…¨çƒç›´è¿"}
  - {ruleset: "DOMAIN-SUFFIX,time.cloudflare.com", group: "ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹"}
  - {ruleset: "DOMAIN-SUFFIX,xn--ngstr-lra8j.com", group: "ğŸ›« å›½é™…å‡ºå‘"}
  - {ruleset: "DOMAIN-SUFFIX,services.googleapis.cn", group: "ğŸ›« å›½é™…å‡ºå‘"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list", group: "ğŸ›« å›½é™…å‡ºå‘"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list", group: "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list", group: "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list", group: "ğŸ“¢ è°·æ­ŒFCM"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list", group: "ğŸ¯ å…¨çƒç›´è¿"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list", group: "ğŸ¯ å…¨çƒç›´è¿"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list", group: "â“‚ï¸ å¾®è½¯Bing"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list", group: "â“‚ï¸ å¾®è½¯äº‘ç›˜"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list", group: "â“‚ï¸ å¾®è½¯æœåŠ¡"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list", group: "ğŸ è‹¹æœæœåŠ¡"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list", group: "ğŸ“² ç”µæŠ¥æ¶ˆæ¯"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list", group: "ğŸ¤– OpenAi"}
  - {ruleset: "https://raw.githubusercontent.com/juewuy/ShellClash/master/rules/ai.list", group: "ğŸ¤– OpenAi"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list", group: "ğŸ¶ ç½‘æ˜“éŸ³ä¹"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list", group: "ğŸ® æ¸¸æˆå¹³å°"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list", group: "ğŸ® æ¸¸æˆå¹³å°"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list", group: "ğŸ® æ¸¸æˆå¹³å°"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list", group: "ğŸ® æ¸¸æˆå¹³å°"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list", group: "ğŸ® æ¸¸æˆå¹³å°"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list", group: "ğŸ“¹ æ²¹ç®¡è§†é¢‘"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list", group: "ğŸ¥ å¥ˆé£è§†é¢‘"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list", group: "ğŸ“º å·´å“ˆå§†ç‰¹"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list", group: "ğŸ“º å“”å“©å“”å“©"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list", group: "ğŸ“º å“”å“©å“”å“©"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list", group: "ğŸŒ å›½å†…åª’ä½“"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list", group: "ğŸŒ å›½å¤–åª’ä½“"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list", group: "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"}
  - {ruleset: "https://raw.githubusercontent.com/UlinoyaPed/ShellClash/dev/lists/proxy.list", group: "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"}
  - {ruleset: "https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/CMBlog.list", group: "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list", group: "ğŸ¯ å…¨çƒç›´è¿"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list", group: "ğŸ¯ å…¨çƒç›´è¿"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list", group: "ğŸ¯ å…¨çƒç›´è¿"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list", group: "ğŸ¯ å…¨çƒç›´è¿"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list", group: "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list", group: "ğŸ¯ å…¨çƒç›´è¿"}
  - {ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list", group: "ğŸ¯ å…¨çƒç›´è¿"}
  - {ruleset: "GEOIP,CN,no-resolve", group: "ğŸ¯ å…¨çƒç›´è¿"}
  - {ruleset: "https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/adobe.list", group: "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"}
  - {ruleset: "FINAL", group: "ğŸ›« å›½é™…å‡ºå‘"}


# ; 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293
# ; 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659, 661, 673, 677, 683, 691
# ;è®¾ç½®åˆ†ç»„æ ‡å¿—ä½

proxy_groups:
  custom_proxy_group:
  - {name: "â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢", type: "select", rule: ["ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹", "ğŸ å…¨éƒ¨èŠ‚ç‚¹", "ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "ğŸ“¶ è¿è¥å•†ä¼˜é€‰"]}
  - {name: "ğŸ›« å›½é™…å‡ºå‘", type: "url-test", rule: ["ğŸ ä½ æ­å–œæˆ‘å‘è´¢æˆ‘æ­å–œä½ ç²¾å½©æœºåœº", "ğŸ‡­ğŸ‡° é¦™æ¸¯å›½é™…æœºåœº", "ğŸ‡¯ğŸ‡µ ä¸œäº¬å›½é™…æœºåœº", "ğŸ‡°ğŸ‡· ä»å·å›½é™…æœºåœº", "ğŸ‡¨ğŸ‡³ ä¸Šæµ·è™¹æ¡¥å›½é™…æœºåœº", "ğŸ‡ºğŸ‡¸ æ´›æ‰çŸ¶å›½é™…æœºåœº", "ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡æ¨Ÿå®œæœºåœº"], url: "http://www.gstatic.com/generate_204", interval: 69100, tolerance: 650}
  - {name: "ğŸ›¬ å›½é™…åˆ°è¾¾", type: "select", rule: ["RelayTarget"]}
  - {name: "ğŸ“¶ è¿è¥å•†ä¼˜é€‰", type: "load-balance", rule: ["^å®˜æ–¹|^CM|CT|CU|CF|ç”µä¿¡|è”é€š|ç§»åŠ¨|VIP"], url: "http://www.gstatic.com/generate_204", interval: 68340, tolerance: 650}
  - {name: "ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", type: "load-balance", rule: ["æ¸¯|HK|hk|Hong Kong|HongKong|hongkong|HKG"], url: "http://www.gstatic.com/generate_204", interval: 64740, tolerance: 650}
  - {name: "ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", type: "load-balance", rule: ["æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|[^-]æ—¥|JP|Japan|Tokyo|NRT|KIX"], url: "http://www.gstatic.com/generate_204", interval: 240, tolerance: 650}
  - {name: "ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", type: "load-balance", rule: ["ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States|ATL|BUF|DFW|EWR|IAD|LAX|MCI|MIA|ORD|PHX|PDX|SEA|SJC"], url: "http://www.gstatic.com/generate_204", interval: 240, tolerance: 650}
  - {name: "ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹", type: "load-balance", rule: ["å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan|TPE|KHH"], url: "http://www.gstatic.com/generate_204", interval: 64140, tolerance: 650}
  - {name: "ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", type: "load-balance", rule: ["æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore|SIN"], url: "http://www.gstatic.com/generate_204", interval: 67340, tolerance: 650}
  - {name: "ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", type: "load-balance", rule: ["KR|Korea|KOR|Seoul|é¦–å°”|æ˜¥å·|éŸ©|éŸ“|ICN"], url: "http://www.gstatic.com/generate_204", interval: 61740, tolerance: 650}
  - {name: "ğŸ å…¨éƒ¨èŠ‚ç‚¹", type: "load-balance", rule: ["æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore|SIN|ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States|ATL|BUF|DFW|EWR|IAD|LAX|MCI|MIA|ORD|PHX|PDX|SEA|SJC|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|[^-]æ—¥|JP|Japan|Tokyo|NRT|KIX|æ¸¯|HK|hk|Hong Kong|HongKong|hongkong|HKG|^å®˜æ–¹|^CM|CT|CU|CF|VIP|ç”µä¿¡|è”é€š|ç§»åŠ¨|KR|Korea|KOR|Seoul|é¦–å°”|æ˜¥å·|éŸ©|éŸ“|ICN"], url: "http://www.gstatic.com/generate_204", interval: 541, tolerance: 650}
  - {name: "ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹", type: "load-balance", rule: ["æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore|SIN|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|[^-]æ—¥|JP|Japan|Tokyo|NRT|KIX|æ¸¯|HK|hk|Hong Kong|HongKong|hongkong|HKG|^å®˜æ–¹|^CM|CT|CU|CF|VIP|ç”µä¿¡|è”é€š|ç§»åŠ¨|KR|Korea|KOR|Seoul|é¦–å°”|æ˜¥å·|éŸ©|éŸ“|ICN"], url: "http://www.gstatic.com/generate_204", interval: 59340, tolerance: 650}
  - {name: "ğŸ“¹ æ²¹ç®¡è§†é¢‘", type: "select", rule: ["ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹", "ğŸ›« å›½é™…å‡ºå‘", "ğŸ å…¨éƒ¨èŠ‚ç‚¹", "â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢", "DIRECT"]}
  - {name: "ğŸš€ èŠ‚ç‚¹é€‰æ‹©", type: "select", rule: ["ğŸ›« å›½é™…å‡ºå‘", "ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹", "ğŸ å…¨éƒ¨èŠ‚ç‚¹", "â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢"]}
  - {name: "ğŸ¤¨ æ•…éšœè½¬ç§»", type: "fallback", rule: ["ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹"], url: "http://www.gstatic.com/generate_204", interval: 55700, tolerance: 650}
  - {name: "ğŸ“² ç”µæŠ¥æ¶ˆæ¯", type: "select", rule: ["ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹", "â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢", "DIRECT"]}
  - {name: "ğŸ¤– OpenAi", type: "select", rule: ["ğŸ›« å›½é™…å‡ºå‘"]}
  - {name: "ğŸ¥ å¥ˆé£è§†é¢‘", type: "select", rule: ["ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹", "â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢", "DIRECT"], custom_rule: "(NF|å¥ˆé£|è§£é”|Netflix|NETFLIX|Media|MITM)"}
  - {name: "ğŸ“º å·´å“ˆå§†ç‰¹", type: "select", rule: ["â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢", "DIRECT"]}
  - {name: "ğŸ“º å“”å“©å“”å“©", type: "select", rule: ["DIRECT"]}
  - {name: "ğŸŒ å›½å¤–åª’ä½“", type: "select", rule: ["ğŸ›« å›½é™…å‡ºå‘", "ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹", "â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢", "DIRECT"], custom_rule: "(MITM)"}
  - {name: "ğŸŒ å›½å†…åª’ä½“", type: "select", rule: ["DIRECT", "ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹", "â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢"]}
  - {name: "ğŸ“¢ è°·æ­ŒFCM", type: "select", rule: ["DIRECT", "ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹", "â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢"]}
  - {name: "â“‚ï¸ å¾®è½¯Bing", type: "select", rule: ["DIRECT", "ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹", "â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢"]}
  - {name: "â“‚ï¸ å¾®è½¯äº‘ç›˜", type: "select", rule: ["DIRECT", "ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹", "â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢"]}
  - {name: "â“‚ï¸ å¾®è½¯æœåŠ¡", type: "select", rule: ["DIRECT", "ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹", "â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢"]}
  - {name: "ğŸ è‹¹æœæœåŠ¡", type: "select", rule: ["DIRECT", "ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹", "â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢"]}
  - {name: "ğŸ® æ¸¸æˆå¹³å°", type: "select", rule: ["DIRECT", "ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹", "â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢"]}
  - {name: "ğŸ¶ ç½‘æ˜“éŸ³ä¹", type: "select", rule: ["DIRECT", "ğŸ›« å›½é™…å‡ºå‘"], custom_rule: "(ç½‘æ˜“|éŸ³ä¹|è§£é”|Music|NetEase)"}
  - {name: "ğŸ¯ å…¨çƒç›´è¿", type: "select", rule: ["DIRECT"]}
  - {name: "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª", type: "select", rule: ["REJECT", "DIRECT"]}
  - {name: "ğŸ‡¨ğŸ‡³ ä¸Šæµ·è™¹æ¡¥å›½é™…æœºåœº", type: "relay", rule: ["ğŸ“¶ è¿è¥å•†ä¼˜é€‰", "ğŸ›¬ å›½é™…åˆ°è¾¾"]}
  - {name: "ğŸ‡­ğŸ‡° é¦™æ¸¯å›½é™…æœºåœº", type: "relay", rule: ["ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "ğŸ›¬ å›½é™…åˆ°è¾¾"]}
  - {name: "ğŸ‡¯ğŸ‡µ ä¸œäº¬å›½é™…æœºåœº", type: "relay", rule: ["ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "ğŸ›¬ å›½é™…åˆ°è¾¾"]}
  - {name: "ğŸ‡°ğŸ‡· ä»å·å›½é™…æœºåœº", type: "relay", rule: ["ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "ğŸ›¬ å›½é™…åˆ°è¾¾"]}
  - {name: "ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡æ¨Ÿå®œæœºåœº", type: "relay", rule: ["ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "ğŸ›¬ å›½é™…åˆ°è¾¾"]}
  - {name: "ğŸ‡ºğŸ‡¸ æ´›æ‰çŸ¶å›½é™…æœºåœº", type: "relay", rule: ["ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "ğŸ›¬ å›½é™…åˆ°è¾¾"]}
  - {name: "ğŸ ä½ æ­å–œæˆ‘å‘è´¢æˆ‘æ­å–œä½ ç²¾å½©æœºåœº", type: "relay", rule: ["ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹", "ğŸ›¬ å›½é™…åˆ°è¾¾"]}

# ;è®¾ç½®åˆ†ç»„æ ‡å¿—ä½

# ;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

# ;luck