version = 1
[common]


[ruleset]
# Enable generating rules with rulesets
enabled = true

# Overwrite the existing rules in rule_base
overwrite_original_rules = true

# Perform a ruleset update on request
update_ruleset_on_request = false

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "[]DOMAIN-SUFFIX,yaoyy.moe"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹"
ruleset = "[]DOMAIN-SUFFIX,time.cloudflare.com"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ›« å›½é™…å‡ºå‘"
ruleset = "[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ›« å›½é™…å‡ºå‘"
ruleset = "[]DOMAIN-SUFFIX,services.googleapis.cn"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ›« å›½é™…å‡ºå‘"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ“¢ è°·æ­ŒFCM"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "â“‚ï¸ å¾®è½¯Bing"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "â“‚ï¸ å¾®è½¯äº‘ç›˜"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "â“‚ï¸ å¾®è½¯æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ è‹¹æœæœåŠ¡"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ“² ç”µæŠ¥æ¶ˆæ¯"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ¤– OpenAi"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ¤– OpenAi"
ruleset = "https://raw.githubusercontent.com/juewuy/ShellClash/master/rules/ai.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ¶ ç½‘æ˜“éŸ³ä¹"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ“¹ æ²¹ç®¡è§†é¢‘"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ¥ å¥ˆé£è§†é¢‘"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ“º å·´å“ˆå§†ç‰¹"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ“º å“”å“©å“”å“©"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ“º å“”å“©å“”å“©"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸŒ å›½å†…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸŒ å›½å¤–åª’ä½“"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/UlinoyaPed/ShellClash/dev/lists/proxy.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/CMBlog.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"
ruleset = "https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/adobe.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "[]GEOIP,CN,no-resolve"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ›« å›½é™…å‡ºå‘"
ruleset = "[]FINAL"
type = "surge-ruleset"
interval = 86400




[[custom_groups]]
name = "â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢"
type = "select"
rule = ["ğŸ ä½ æ­å–œæˆ‘å‘è´¢æˆ‘æ­å–œä½ ç²¾å½©æœºåœº", "ğŸ‡­ğŸ‡° é¦™æ¸¯å›½é™…æœºåœº", "ğŸ‡¯ğŸ‡µ ä¸œäº¬å›½é™…æœºåœº", "ğŸ‡°ğŸ‡· ä»å·å›½é™…æœºåœº", "ğŸ‡¨ğŸ‡³ ä¸Šæµ·è™¹æ¡¥å›½é™…æœºåœº", "ğŸ‡ºğŸ‡¸ æ´›æ‰çŸ¶å›½é™…æœºåœº", "ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡æ¨Ÿå®œæœºåœº", "ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹", "ğŸ å…¨éƒ¨èŠ‚ç‚¹", "ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "ğŸ“¶ è¿è¥å•†ä¼˜é€‰"]
disable_udp = false

[[custom_groups]]
name = "ğŸ›« å›½é™…å‡ºå‘"
type = "url-test"
rule = ["ğŸ ä½ æ­å–œæˆ‘å‘è´¢æˆ‘æ­å–œä½ ç²¾å½©æœºåœº", "ğŸ‡­ğŸ‡° é¦™æ¸¯å›½é™…æœºåœº", "ğŸ‡¯ğŸ‡µ ä¸œäº¬å›½é™…æœºåœº", "ğŸ‡°ğŸ‡· ä»å·å›½é™…æœºåœº", "ğŸ‡¨ğŸ‡³ ä¸Šæµ·è™¹æ¡¥å›½é™…æœºåœº", "ğŸ‡ºğŸ‡¸ æ´›æ‰çŸ¶å›½é™…æœºåœº", "ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡æ¨Ÿå®œæœºåœº"]
url = "http://www.gstatic.com/generate_204"
interval = 673
tolerance = 50
lazy = false

[[custom_groups]]
name = "ğŸ›¬ å›½é™…åˆ°è¾¾"
type = "select"
rule = ["RelayTarget"]
disable_udp = false

[[custom_groups]]
name = "ğŸ“¶ è¿è¥å•†ä¼˜é€‰"
type = "load-balance"
rule = ["^å®˜æ–¹|^CM|CT|CU|CF|ç”µä¿¡|è”é€š|ç§»åŠ¨|VIP"]
interval = 6130
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹"
type = "load-balance"
rule = ["æ¸¯|HK|hk|Hong Kong|HongKong|hongkong|HKG"]
interval = 5990
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹"
type = "load-balance"
rule = ["æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|[^-]æ—¥|JP|Japan|Tokyo|NRT|KIX"]
interval = 6190
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹"
type = "load-balance"
rule = ["ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States|ATL|BUF|DFW|EWR|IAD|LAX|MCI|MIA|ORD|PHX|PDX|SEA|SJC"]
interval = 641
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹"
type = "load-balance"
rule = ["å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan|TPE|KHH"]
interval = 6170
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹"
type = "load-balance"
rule = ["æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore|SIN"]
interval = 6770
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹"
type = "load-balance"
rule = ["KR|Korea|KOR|Seoul|é¦–å°”|æ˜¥å·|éŸ©|éŸ“|ICN"]
interval = 6830
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸ å…¨éƒ¨èŠ‚ç‚¹"
type = "load-balance"
rule = ["æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore|SIN|ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States|ATL|BUF|DFW|EWR|IAD|LAX|MCI|MIA|ORD|PHX|PDX|SEA|SJC|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|[^-]æ—¥|JP|Japan|Tokyo|NRT|KIX|æ¸¯|HK|hk|Hong Kong|HongKong|hongkong|HKG|^å®˜æ–¹|^CM|CT|CU|CF|VIP|ç”µä¿¡|è”é€š|ç§»åŠ¨|KR|Korea|KOR|Seoul|é¦–å°”|æ˜¥å·|éŸ©|éŸ“|ICN"]
interval = 641
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹"
type = "load-balance"
rule = ["æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore|SIN|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|[^-]æ—¥|JP|Japan|Tokyo|NRT|KIX|æ¸¯|HK|hk|Hong Kong|HongKong|hongkong|HKG|^å®˜æ–¹|^CM|CT|CU|CF|VIP|ç”µä¿¡|è”é€š|ç§»åŠ¨|KR|Korea|KOR|Seoul|é¦–å°”|æ˜¥å·|éŸ©|éŸ“|ICN"]
interval = 6910
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸ“¹ æ²¹ç®¡è§†é¢‘"
type = "select"
rule = ["ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹", "ğŸ›« å›½é™…å‡ºå‘", "ğŸ å…¨éƒ¨èŠ‚ç‚¹", "â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢", "DIRECT"]
disable_udp = false

[[custom_groups]]
name = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
type = "select"
rule = ["ğŸ›« å›½é™…å‡ºå‘", "ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹", "ğŸ å…¨éƒ¨èŠ‚ç‚¹", "â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢"]
disable_udp = false

[[custom_groups]]
name = "ğŸ¤¨ æ•…éšœè½¬ç§»"
type = "fallback"
rule = ["ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹", "ğŸ›« å›½é™…å‡ºå‘", "ğŸ å…¨éƒ¨èŠ‚ç‚¹"]
url = "http://www.gstatic.com/generate_204"
interval = 293
tolerance = 50

[[custom_groups]]
name = "ğŸ“² ç”µæŠ¥æ¶ˆæ¯"
type = "select"
rule = ["ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹", "ğŸ›« å›½é™…å‡ºå‘", "ğŸ å…¨éƒ¨èŠ‚ç‚¹", "â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢", "DIRECT"]
disable_udp = false

[[custom_groups]]
name = "ğŸ¤– OpenAi"
type = "select"
rule = ["ğŸ›« å›½é™…å‡ºå‘"]
disable_udp = false

[[custom_groups]]
name = "ğŸ¥ å¥ˆé£è§†é¢‘"
type = "select"
rule = ["ğŸ›« å›½é™…å‡ºå‘", "ğŸ å…¨éƒ¨èŠ‚ç‚¹", "â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢", "DIRECT"]
disable_udp = false

[[custom_groups]]
name = "ğŸ“º å·´å“ˆå§†ç‰¹"
type = "select"
rule = ["â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢", "DIRECT"]
disable_udp = false

[[custom_groups]]
name = "ğŸ“º å“”å“©å“”å“©"
type = "select"
rule = ["DIRECT"]
disable_udp = false

[[custom_groups]]
name = "ğŸŒ å›½å¤–åª’ä½“"
type = "select"
rule = ["ğŸ›« å›½é™…å‡ºå‘", "ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹", "â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢", "DIRECT"]
disable_udp = false

[[custom_groups]]
name = "ğŸŒ å›½å†…åª’ä½“"
type = "select"
rule = ["DIRECT", "ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹", "â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢"]
disable_udp = false

[[custom_groups]]
name = "ğŸ“¢ è°·æ­ŒFCM"
type = "select"
rule = ["DIRECT", "ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹", "â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢"]
disable_udp = false

[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯Bing"
type = "select"
rule = ["DIRECT", "ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹", "â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢"]
disable_udp = false

[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯äº‘ç›˜"
type = "select"
rule = ["DIRECT", "ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹", "â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢"]
disable_udp = false

[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯æœåŠ¡"
type = "select"
rule = ["DIRECT", "ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹", "â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢"]
disable_udp = false

[[custom_groups]]
name = "ğŸ è‹¹æœæœåŠ¡"
type = "select"
rule = ["DIRECT", "ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹", "â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢"]
disable_udp = false

[[custom_groups]]
name = "ğŸ® æ¸¸æˆå¹³å°"
type = "select"
rule = ["DIRECT", "ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹", "â˜‘ï¸ æ‰‹åŠ¨åˆ‡æ¢"]
disable_udp = false

[[custom_groups]]
name = "ğŸ¶ ç½‘æ˜“éŸ³ä¹"
type = "select"
rule = ["DIRECT", "ğŸ›« å›½é™…å‡ºå‘"]
disable_udp = false

[[custom_groups]]
name = "ğŸ¯ å…¨çƒç›´è¿"
type = "select"
rule = ["DIRECT"]
disable_udp = false

[[custom_groups]]
name = "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"
type = "select"
rule = ["REJECT", "DIRECT"]
disable_udp = false

[[custom_groups]]
name = "ğŸ‡¨ğŸ‡³ ä¸Šæµ·è™¹æ¡¥å›½é™…æœºåœº"
type = "relay"
rule = ["ğŸ“¶ è¿è¥å•†ä¼˜é€‰", "ğŸ›¬ å›½é™…åˆ°è¾¾"]
disable_udp = false

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° é¦™æ¸¯å›½é™…æœºåœº"
type = "relay"
rule = ["ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "ğŸ›¬ å›½é™…åˆ°è¾¾"]
disable_udp = false

[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µ ä¸œäº¬å›½é™…æœºåœº"
type = "relay"
rule = ["ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "ğŸ›¬ å›½é™…åˆ°è¾¾"]
disable_udp = false

[[custom_groups]]
name = "ğŸ‡°ğŸ‡· ä»å·å›½é™…æœºåœº"
type = "relay"
rule = ["ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "ğŸ›¬ å›½é™…åˆ°è¾¾"]
disable_udp = false

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡æ¨Ÿå®œæœºåœº"
type = "relay"
rule = ["ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "ğŸ›¬ å›½é™…åˆ°è¾¾"]
disable_udp = false

[[custom_groups]]
name = "ğŸ‡ºğŸ‡¸ æ´›æ‰çŸ¶å›½é™…æœºåœº"
type = "relay"
rule = ["ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "ğŸ›¬ å›½é™…åˆ°è¾¾"]
disable_udp = false

[[custom_groups]]
name = "ğŸ ä½ æ­å–œæˆ‘å‘è´¢æˆ‘æ­å–œä½ ç²¾å½©æœºåœº"
type = "relay"
rule = ["ğŸ‡ºğŸ‡³ äºšå¤ªèŠ‚ç‚¹", "ğŸ›¬ å›½é™…åˆ°è¾¾"]
disable_udp = false
